# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: hangaebal blog
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Jekyll 활용 GitHub blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hangaebal.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: hangaebal

# Build settings
markdown: kramdown


repository: hangaebal/hangaebal.github.io